---
title: "Q1"
output: pdf_notebook
---

```{r}
setwd("~/R/MATH551/TakeHomeTest")
library(tidyverse)
load("./testData.Rdata")
```


# Question 1
## a
```{r}
ll_1_a <- function(para, datavec, choice = 1) {
  n <- length(datavec)
  b <- para[1] 
  g <- para[2]

  z <- n * log(2) - n * log(gamma(0.25)) + 0.25 * n * log(b) - b * sum((datavec - g)^4)

  if (choice > 0) {

    return(z)

  } else {

    return(-z)

  }
}

ll_nc_1_a <- function(para, datavec, choice = 1) {
  n <- length(datavec)
  b <- para[1] 
  g <- para[2]

  z <-  0.25 * n * log(b) - b * sum((datavec - g)^4)
  
  if (choice > 0) {

    return(z)

  } else {

    return(-z)

  }
  
}

ll_1_a(c(2, 4), quarry)
ll_nc_1_a(c(2, 4), quarry)
```

## b
```{r}
fit_b <- optim(c(2, 4), ll_1_a, method = "Nelder-Mead", datavec = quarry, choice = -1, hessian = T)
fit_b
```

## c
```{r}
fit_c <- optim(c(2, 4), ll_1_a, method = "Nelder-Mead", datavec = quarry, choice = -1, hessian = T)
fit_c
```

## d
```{r}
length(quarry) / (4 * fit_c$par[1]^2)
-4 * sum((quarry - fit_c$par[2])^3)
12 * fit_c$par[1] * (sum((quarry - fit_c$par[2])^2))
```

## e
```{r}
# I_o
I_o <- fit_c$hessian
# 1
I_o_m <- solve(I_o)
se_1 <- sqrt(I_o_m[4])
se_1
cilo_1 <- fit_c$par[2] - 1.96 * se_1
cihi_1 <- fit_c$par[2] + 1.96 * se_1
print(c(cilo_1, cihi_1))

# 2
I_o_gamma <- I_o[4]
var <- 1 / I_o_gamma
se_2 <- sqrt(var)
cilo_2 <- fit_c$par[2] - 1.96 * se_2
cihi_2 <- fit_c$par[2] + 1.96 * se_2
print(c(cilo_2, cihi_2))
```

# f
```{r}
gamma_hat <- fit_c$par[2]
gamma_hat
n <- length(quarry)
beta_hat <- n / (4 * sum((quarry - gamma_hat)^4))
beta_hat
mle <- ll_1_a(c(beta_hat, gamma_hat), quarry)
mle
```

# g
```{r}
gamma_g <- seq(4.5, 5.5, length = 2000)
Pl_gamma_function <- function(r, datavec) {
  n <- length(datavec)
  z <- 0.25 * n * log(n / (4 * sum((datavec - r)^4))) - n / 4
  return(z)
}

Pl_gamma_function_deviance <- function(r, datavec) {

  z <- 2 * (Pl_gamma_function(fit_c$par[2], datavec) - Pl_gamma_function(r, datavec))

  return(z)
}

plot(gamma_g, sapply(gamma_g, Pl_gamma_function_deviance, datavec = quarry), type="l", ylab = "Deviance", xlab = "Lambda")
abline(h=3.84, col="red")

optim_root_Pl_lambda_function_deviance <- function(par, data) {

  z <- ((2 * (Pl_lambda_function(fit_iii$par, data, choice = 1) - Pl_lambda_function(par, data, choice = 1))) - 3.84)^2

  return(z)
}

optim_root_Pl_gamma_function_deviance <- function(par, data) {

  z <- ((2 * (Pl_gamma_function(fit_c$par[2], data) - Pl_gamma_function(par, data))) - 3.84)^2

  return(z)
}

gamma_root_min <- optim(4.8, optim_root_Pl_gamma_function_deviance, method = "Brent", lower = 4.8, upper = 5.0, data = quarry)

gamma_root_max <- optim(5.0, optim_root_Pl_gamma_function_deviance, method = "Brent", lower = 5.0, upper = 5.2, data = quarry)

print(paste(gamma_root_min$par, ",", gamma_root_max$par))
abline(v=gamma_root_min$par, col="red")
abline(v=gamma_root_max$par, col="red")
```
