---
title: "Q2"
author: "Congye"
date: "10/14/2020"
---

```{r, include=FALSE}
library(tidyverse)
setwd("~/R/MATH551/Quiz/Quiz2/")
load("../M551Quiz2018.Rdata")
source("../hessian.R")
```

# i
```{r}
uniform.loglik <- function(para, data) {
  # para[1] = lambda
  # para[2] = p

  z <- sum(
    lfactorial(data + para[1] - 1) 
    - lfactorial(data) 
    - lfactorial(para[1] - 1) 
    + data * log(1 - para[2]) 
    + para[1] * log(para[2]))

  return(z)
}

para_i_1 <- c(4, 0.25)
para_i_2 <- c(3, 0.5)
uniform.loglik(para_i_1, caterpillars)
uniform.loglik(para_i_2, caterpillars)
```
So, the result of $l(4,.25)$ is `r uniform.loglik(para_1, caterpillars)`, the result of $l(3,0.5)$ is `r uniform.loglik(para_2, caterpillars)`

# ii
```{r}
lambda_ii <- 3
p_ii <- lambda_ii/(mean(caterpillars)+lambda_ii)
print(p_ii)
```

# iii
```{r}
lambda_iii <- seq(2, 50, length = 2000)
Pl_lambda_function <- function(lambda, data, choice = 1) {

  z <- sum(
    log(
      (factorial(data + lambda - 1) / (factorial(data) * factorial(lambda - 1))) * ((1 - lambda / (mean(data) + lambda))^data) * ((lambda / (mean(data) + lambda))^lambda)
    )
  )
  
  if (choice > 0) {
    return(z)
  }
  else{
    return(-z)
  }

}

Pl <- sapply(lambda_iii, Pl_lambda_function, data = caterpillars)
plot(lambda_iii, Pl, type = "l")
# Pl
set.seed(4321^2)
fit_iii <- optim(2, Pl_lambda_function, method = "Brent", lower = 2, upper = 50, data = caterpillars, choice = -1, hessian = TRUE)
fit_iii
```
As a result, $\hat{\lambda}$ is `r fit_iii$par`, and MLE is `r fit_iii$value`.

# iv
```{r}
p_iv <- fit_iii$par / (mean(caterpillars) + fit_iii$par)
p_iv
```
# v
```{r}
Pl_lambda_function_deviance <- function(par, data) {

  z <- 2 * (Pl_lambda_function(fit_iii$par, data, choice = 1) - Pl_lambda_function(par, data, choice = 1))
  
  return(z)
}

plot(lambda_iii, sapply(lambda_iii, Pl_lambda_function_deviance, data = caterpillars), type="l", ylab = "Deviance", xlab = "Lambda")
abline(h=3.84, col="red")

#Find_root <- data.frame(
#  x=lambda_iii,
#  y=(sapply(lambda_iii, Pl_lambda_function_deviance, data = caterpillars) - rep(3.84, #length(lambda_iii)))^2)

#which.min(Find_root$y)
########################################################################
optim_root_Pl_lambda_function_deviance <- function(par, data) {

  z <- ((2 * (Pl_lambda_function(fit_iii$par, data, choice = 1) - Pl_lambda_function(par, data, choice = 1))) - 3.84)^2

  return(z)
}
lambda_root_min <- optim(2.2, optim_root_Pl_lambda_function_deviance, method = "Brent", lower = 2.2, upper = 3, data = caterpillars)

lambda_root_max <- optim(5, optim_root_Pl_lambda_function_deviance, method = "Brent", lower = 5, upper = 50, data = caterpillars)

print(paste(lambda_root_min$par, ",", lambda_root_max$par))
abline(v=lambda_root_min$par, col="red")
abline(v=lambda_root_max$par, col="red")
```

# vi
```{r}
I_o <- matrix(c(8.34, -252, -252, 7750), nrow = 2, ncol = 2)
I_o_m1 <- solve(I_o)
se <- sqrt(I_o_m1[1])
se
```

# vii
```{r}
cilo <- fit_iii$par - 1.96 * se
cihi <- fit_iii$par + 1.96 * se
print(c(cilo, cihi))
```

# viii
```{r}
four_test <- function(para_0, para_hat, data, I){
  # Score Test
  W1 <- Pl_lambda_function(para_0, data) * I^(-1) * Pl_lambda_function(para_0, data)
  p1 <- 1 - pchisq(W1, df = 1)
  
  # Wald Test
  W2 <- (para_hat - para_0) *  I * (para_hat - para_0)
  p2 <- 1 - pchisq(W2, df = 1)
  
  # Likelihood Ratio Tets
  W3 <- 2 * Pl_lambda_function_deviance(para_0, data)
  p3 <- 1 - pchisq(W3, df = 1)
  
  # MLE
  Z <- (para_hat - para_0) / sqrt(I)
  pz <- 1 - pnorm(Z)
  
  df <- data.frame(W1=W1, p1=p1, W2=W2, p2=p2, W3=W3, p3=p3, Z=Z, pz=pz)
  return(df)
}

lambda0_viii <- 40
four_test(lambda0_viii, fit_iii$par, caterpillars, I_o[1])
```

# ix
```{r}
four_test(20, fit_iii$par, caterpillars, I_o_m1[1])
```